### ISSUE TITLE
Invalid Response

### ISSUE THREAD

**Issue by fayas-akram** [devmehq/email-validator-js#147]
{
    "validFormat": false,
    "validSmtp": null,
    "validMx": null
}

**Comment by golyalpha** [comment]
Sounds like an OK-ish response to me. The provided email address didn't have valid format, so the SMTP and MX Records check weren't made - hence `validSmtp` and `validMx` are both null.

**Comment by 1-osama-1** [comment]
It display the similar response even if i enter the correct email

const { verifyEmail } = require('@devmehq/email-validator-js');

verifyEmail({
  mailbox: 'pakipower44556@gmail.com',
  verifyMx: true,
  verifySmtp: true,
  timeout: 3000
}).then(result => {
  console.log(result);
}).catch(error => {
  console.error(error);
});


Output:

{ validFormat: false, validMx: null, validSmtp: null }
