### ISSUE TITLE
Can't resolve 'dns' in ./node_modules/@devmehq/email-validator-js/dist/dns.js

### ISSUE THREAD

**Issue by diennn-gg** [devmehq/email-validator-js#218]
I have an error: Can't resolve 'dns' in ./node_modules/@devmehq/email-validator-js/dist/dns.js.
Nodejs: v18.

Please help to resolve this error. Thanks

**Comment by YPCrumble** [comment]
The full error includes:

> Did you mean './dns'
> Requests that resolve in the current directory need to start with './'.

This is using Webpack for compilation.

**Comment by meabed** [comment]
Can you make a repo or codesanbox that reproduce the issue

**Comment by diennn-gg** [comment]
I send demo link at here @meabed 
https://codesandbox.io/p/sandbox/demo-dnzly5?file=%2Fsrc%2FApp.js

**Comment by YPCrumble** [comment]
Is it possible that this package's `dns.ts` is conflicting with node's builtin `dns` module? And that renaming this package's `dns.ts` to something like `dns-records.ts` would solve the issue?

**Comment by meabed** [comment]
@YPCrumble @diennn-gg 

This issue is due to the dns module in nodejs not available in browser / client side.

This library is meant to be used in backend services not in the browser.
